<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HMailServer.Search.SqlServer</AssemblyName>
    <RootNamespace>HMailServer.Search.SqlServer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HMailServer.Core\HMailServer.Core.csproj" />
  </ItemGroup>
</Project>
