<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>HMailServer.Scripting</AssemblyName>
    <RootNamespace>HMailServer.Scripting</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HMailServer.Core\HMailServer.Core.csproj" />
  </ItemGroup>
</Project>
