namespace HMailServer.Core.Abstractions;

public sealed record AccountAdministrationSnapshot(
    int Id,
    int DomainId,
    string Address,
    bool Active,
    int AdminLevel,
    int MaxSize = 0,
    float Size = 0f,
    string PersonFirstName = "",
    string PersonLastName = "",
    bool VacationMessageIsOn = false,
    string VacationMessage = "",
    string VacationSubject = "",
    bool VacationMessageExpires = false,
    string VacationMessageExpiresDate = "",
    bool VacationMessageAbortSpamFlagged = false,
    bool ForwardEnabled = false,
    string ForwardAddress = "",
    bool ForwardKeepOriginal = false,
    bool ForwardAbortSpamFlagged = false,
    bool SignatureEnabled = false,
    string SignaturePlainText = "",
    string SignatureHtml = "");
