namespace HMailServer.Core.Abstractions;

public sealed record DomainAdministrationSnapshot(
    int Id,
    string Name,
    bool Active,
    string Postmaster = "",
    int MaxMessageSize = 0,
    bool PlusAddressingEnabled = false,
    string PlusAddressingCharacter = "",
    bool AntiSpamEnableGreylisting = false,
    string AdDomainName = "",
    int MaxSize = 0,
    long AllocatedSize = 0,
    int MaxNumberOfAccounts = 0,
    int MaxNumberOfAliases = 0,
    int MaxNumberOfDistributionLists = 0,
    bool MaxNumberOfAccountsEnabled = false,
    bool MaxNumberOfAliasesEnabled = false,
    bool MaxNumberOfDistributionListsEnabled = false,
    int MaxAccountSize = 0,
    bool SignatureEnabled = false,
    int SignatureMethod = 1,
    string SignaturePlainText = "",
    string SignatureHtml = "",
    bool AddSignaturesToReplies = false,
    bool AddSignaturesToLocalMail = true,
    bool DkimSignEnabled = false,
    string DkimSelector = "",
    string DkimPrivateKeyFile = "",
    int DkimHeaderCanonicalizationMethod = 2,
    int DkimBodyCanonicalizationMethod = 2,
    int DkimSigningAlgorithm = 2,
    bool DkimSignAliasesEnabled = false);
