namespace HMailServer.Core.Abstractions;

public sealed record ScriptAccount(
    int AccountId,
    string Address,
    bool Active,
    bool IsActiveDirectoryAccount,
    int DomainId,
    string ActiveDirectoryDomain,
    string ActiveDirectoryUsername,
    int MaxSizeMegabytes,
    string PersonFirstName,
    string PersonLastName,
    int AdminLevel,
    bool VacationMessageIsOn,
    string VacationMessage,
    string VacationSubject,
    bool VacationMessageExpires,
    string VacationMessageExpiresDate,
    bool VacationMessageAbortSpamFlagged,
    bool ForwardEnabled,
    string ForwardAddress,
    bool ForwardKeepOriginal,
    bool ForwardAbortSpamFlagged,
    bool SignatureEnabled,
    string SignaturePlainText,
    string SignatureHtml,
    string LastLogonTime);
