namespace HMailServer.Core.Abstractions;

public sealed record SettingsAdministrationSnapshot(
    string HostName,
    string WelcomeSmtp,
    string WelcomePop3,
    string WelcomeImap,
    int MaxSmtpConnections = 0,
    int MaxPop3Connections = 0,
    int MaxImapConnections = 0,
    int MaxDeliveryThreads = 0,
    bool ServiceSmtp = false,
    bool ServicePop3 = false,
    bool ServiceImap = false,
    int SmtpNoOfTries = 0,
    int SmtpMinutesBetweenTry = 0,
    int MaxMessageSize = 0,
    int MaxSmtpRecipientsInBatch = 0,
    bool DisconnectInvalidClients = false,
    int MaxNumberOfInvalidCommands = 0,
    bool ImapSortEnabled = false,
    bool ImapQuotaEnabled = false,
    bool ImapIdleEnabled = false,
    bool ImapAclEnabled = false,
    bool ImapSaslPlainEnabled = false,
    bool ImapSaslInitialResponseEnabled = false,
    string ImapPublicFolderName = "",
    string ImapHierarchyDelimiter = "",
    bool AllowSmtpAuthPlain = false,
    bool AllowMailFromNull = false,
    bool AllowIncorrectLineEndings = false,
    bool AddDeliveredToHeader = false,
    string MirrorEmailAddress = "",
    string DefaultDomain = "",
    string SmtpDeliveryBindToIp = "",
    int RuleLoopLimit = 0,
    int WorkerThreadPriority = 0,
    int TcpIpThreads = 0,
    int MaxNumberOfMxHosts = 0,
    bool VerifyRemoteSslCertificate = false,
    string SslCipherList = "",
    bool Ipv6PreferredEnabled = false,
    bool AutoBanOnLogonFailure = false,
    int MaxInvalidLogonAttempts = 0,
    int MaxInvalidLogonAttemptsWithin = 0,
    int AutoBanMinutes = 0,
    string SmtpRelayer = "",
    bool SmtpRelayerRequiresAuthentication = false,
    string SmtpRelayerUsername = "",
    int SmtpRelayerPort = 0,
    int SmtpRelayerConnectionSecurity = 0,
    int SmtpConnectionSecurity = 0,
    int SslVersions = 0,
    int TlsOptions = 0,
    string ImapMasterUser = "",
    int MaxAsynchronousThreads = 0,
    int LoggingMask = 0,
    int LogDevice = 0,
    int LogFormat = 0,
    bool AwStatsEnabled = false,
    bool UseScriptServer = false,
    string ScriptLanguage = "",
    string BackupDestination = "",
    int BackupOptions = 0);
